print ("Getting to know you!")
print()
strName=input ("What's your name?:")
strFood=input ("What's your favourite food?:")
strMusic=input ("What's your favourite music?:")
strLive=input ("Where do you live?:")
print()
print ("You are")
print(strName)
print("You're probably hungry for")
print(strFood)
print("and you're definitely getting your groove on to")
print(strMusic)
print("living in the amazing")
print(strLive)