print("MENU")
print("")
strFood=input("Name a food > ")
strPlant=input("Name a type of plant > ")
strCooking=input("Name a method of cooking > ")
strBurnedWord=input("What word describes burned food? > ")
strDiyItem=input("Name a DIY item > ")
print(strCooking, strFood, "with ", strBurnedWord, strPlant, "on a bed of ", strDiyItem)